{
    Copyright 2001-2008, Estate of Peter Millard
	
	This file is part of Exodus.
	
	Exodus is free software; you can redistribute it and/or modify
	it under the terms of the GNU General Public License as published by
	the Free Software Foundation; either version 2 of the License, or
	(at your option) any later version.
	
	Exodus is distributed in the hope that it will be useful,
	but WITHOUT ANY WARRANTY; without even the implied warranty of
	MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
	GNU General Public License for more details.
	
	You should have received a copy of the GNU General Public License
	along with Exodus; if not, write to the Free Software
	Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA
}
unit COMExControls;



{-----------------------------------------------------------------------------}
{-----------------------------------------------------------------------------}
{ This is autogenerated code using the COMGuiGenerator. DO NOT MODIFY BY HAND }
{-----------------------------------------------------------------------------}
{-----------------------------------------------------------------------------}


{$WARN SYMBOL_PLATFORM OFF}

interface
uses
    ActiveX,Classes,ComObj,Controls,Exodus_TLB,Forms,StdCtrls,StdVcl;

function getCOMControl(o: TObject): IExodusControl;

implementation
uses
    Buttons,ComCtrls,COMExBitBtn,COMExButton,COMExCheckBox,COMExComboBox,COMExEdit,COMExFont,COMExForm,COMExLabel,COMExListBox,COMExMainMenu,COMExMemo,COMExMenuItem,COMExPageControl,COMExPanel,COMExPopupMenu,COMExRadioButton,COMExRichEdit,COMExSpeedButton,ExtCtrls,Graphics,Menus,TntButtons,TntComCtrls,TntExtCtrls,TntMenus,TntStdCtrls, ExRichEdit;

function getCOMControl(o: TObject): IExodusControl;
begin
    if (o = nil) then begin
        Result := nil;
        exit;
    end;
    if (o is TFont) then begin 
        Result := IExodusControl(TExControlFont.Create(TFont(o)));
        exit;
    end;
    if (o is TForm) then begin 
        Result := IExodusControl(TExControlForm.Create(TForm(o)));
        exit;
    end;
    if ((o is TTntPanel) or (o is TPanel)) then begin
        Result := IExodusControl(TExControlPanel.Create(TTntPanel(o)));
        exit;
    end;
    if ((o is TTntMenuItem) or (o is TMenuItem)) then begin
        Result := IExodusControl(TExControlMenuItem.Create(TTntMenuItem(o)));
        exit;
    end;
    if ((o is TTntPopupMenu) or (o is TPopupMenu)) then begin
        Result := IExodusControl(TExControlPopupMenu.Create(TTntPopupMenu(o)));
        exit;
    end;
    if ((o is TTntMainMenu) or (o is TMainMenu)) then begin
        Result := IExodusControl(TExControlMainMenu.Create(TTntMainMenu(o)));
        exit;
    end;
    if ((o is TTntButton) or (o is TButton)) then begin
        Result := IExodusControl(TExControlButton.Create(TTntButton(o)));
        exit;
    end;
    if ((o is TTntBitBtn) or (o is TBitBtn)) then begin
        Result := IExodusControl(TExControlBitBtn.Create(TTntBitBtn(o)));
        exit;
    end;
    if ((o is TTntSpeedButton) or (o is TSpeedButton)) then begin
        Result := IExodusControl(TExControlSpeedButton.Create(TTntSpeedButton(o)));
        exit;
    end;
    if ((o is TTntLabel) or (o is TLabel)) then begin
        Result := IExodusControl(TExControlLabel.Create(TTntLabel(o)));
        exit;
    end;
    if ((o is TTntEdit) or (o is TEdit)) then begin
        Result := IExodusControl(TExControlEdit.Create(TTntEdit(o)));
        exit;
    end;
    if ((o is TTntCheckBox) or (o is TCheckBox)) then begin
        Result := IExodusControl(TExControlCheckBox.Create(TTntCheckBox(o)));
        exit;
    end;
    if ((o is TTntRadioButton) or (o is TRadioButton)) then begin
        Result := IExodusControl(TExControlRadioButton.Create(TTntRadioButton(o)));
        exit;
    end;
    if ((o is TTntListBox) or (o is TListBox)) then begin
        Result := IExodusControl(TExControlListBox.Create(TTntListBox(o)));
        exit;
    end;
    if ((o is TTntComboBox) or (o is TComboBox)) then begin
        Result := IExodusControl(TExControlComboBox.Create(TTntComboBox(o)));
        exit;
    end;
    if ((o is TTntMemo) or (o is TMemo)) then begin
        Result := IExodusControl(TExControlMemo.Create(TTntMemo(o)));
        exit;
    end;
    if ((o is TTntPageControl) or (o is TPageControl)) then begin
        Result := IExodusControl(TExControlPageControl.Create(TTntPageControl(o)));
        exit;
    end;
    if ((o is TRichEdit)or (o is TExRichEdit)) then begin
        Result := IExodusControl(TExControlRichEdit.Create(TRichEdit(o)));
        exit;
    end;
end;

end.
