{
    Copyright 2001-2008, Estate of Peter Millard
	
	This file is part of Exodus.
	
	Exodus is free software; you can redistribute it and/or modify
	it under the terms of the GNU General Public License as published by
	the Free Software Foundation; either version 2 of the License, or
	(at your option) any later version.
	
	Exodus is distributed in the hope that it will be useful,
	but WITHOUT ANY WARRANTY; without even the implied warranty of
	MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
	GNU General Public License for more details.
	
	You should have received a copy of the GNU General Public License
	along with Exodus; if not, write to the Free Software
	Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA
}
unit COMExBitBtn;



{-----------------------------------------------------------------------------}
{-----------------------------------------------------------------------------}
{ This is autogenerated code using the COMGuiGenerator. DO NOT MODIFY BY HAND }
{-----------------------------------------------------------------------------}
{-----------------------------------------------------------------------------}


{$WARN SYMBOL_PLATFORM OFF}

interface
uses
    ActiveX,Buttons,Classes,COMExFont,COMExPopupMenu,ComObj,Controls,Exodus_TLB,Forms,Graphics,StdCtrls,StdVcl,TntButtons,TntMenus;

type
    TExControlBitBtn = class(TAutoObject, IExodusControl, IExodusControlBitBtn)
    public
        constructor Create(control: TTntBitBtn);

    private
        _control: TTntBitBtn;

    protected
        function Get_ControlType: ExodusControlTypes; safecall;
        function Get_Name: Widestring; safecall;
        procedure Set_Name(const Value: Widestring); safecall;
        function Get_Tag: Integer; safecall;
        procedure Set_Tag(Value: Integer); safecall;
        function Get_Left: Integer; safecall;
        procedure Set_Left(Value: Integer); safecall;
        function Get_Top: Integer; safecall;
        procedure Set_Top(Value: Integer); safecall;
        function Get_Width: Integer; safecall;
        procedure Set_Width(Value: Integer); safecall;
        function Get_Height: Integer; safecall;
        procedure Set_Height(Value: Integer); safecall;
        function Get_Cursor: Integer; safecall;
        procedure Set_Cursor(Value: Integer); safecall;
        function Get_Hint: Widestring; safecall;
        procedure Set_Hint(const Value: Widestring); safecall;
        function Get_HelpType: Integer; safecall;
        procedure Set_HelpType(Value: Integer); safecall;
        function Get_HelpKeyword: Widestring; safecall;
        procedure Set_HelpKeyword(const Value: Widestring); safecall;
        function Get_HelpContext: Integer; safecall;
        procedure Set_HelpContext(Value: Integer); safecall;
        function Get_BiDiMode: Integer; safecall;
        procedure Set_BiDiMode(Value: Integer); safecall;
        function Get_Cancel: Integer; safecall;
        procedure Set_Cancel(Value: Integer); safecall;
        function Get_Caption: Widestring; safecall;
        procedure Set_Caption(const Value: Widestring); safecall;
        function Get_Default: Integer; safecall;
        procedure Set_Default(Value: Integer); safecall;
        function Get_DragCursor: Integer; safecall;
        procedure Set_DragCursor(Value: Integer); safecall;
        function Get_DragKind: Integer; safecall;
        procedure Set_DragKind(Value: Integer); safecall;
        function Get_DragMode: Integer; safecall;
        procedure Set_DragMode(Value: Integer); safecall;
        function Get_Enabled: Integer; safecall;
        procedure Set_Enabled(Value: Integer); safecall;
        function Get_Font: IExodusControlFont; safecall;
        function Get_ModalResult: Integer; safecall;
        procedure Set_ModalResult(Value: Integer); safecall;
        function Get_ParentBiDiMode: Integer; safecall;
        procedure Set_ParentBiDiMode(Value: Integer); safecall;
        function Get_ParentFont: Integer; safecall;
        procedure Set_ParentFont(Value: Integer); safecall;
        function Get_ParentShowHint: Integer; safecall;
        procedure Set_ParentShowHint(Value: Integer); safecall;
        function Get_PopupMenu: IExodusControlPopupMenu; safecall;
        function Get_ShowHint: Integer; safecall;
        procedure Set_ShowHint(Value: Integer); safecall;
        function Get_TabOrder: Integer; safecall;
        procedure Set_TabOrder(Value: Integer); safecall;
        function Get_TabStop: Integer; safecall;
        procedure Set_TabStop(Value: Integer); safecall;
        function Get_Visible: Integer; safecall;
        procedure Set_Visible(Value: Integer); safecall;
        function Get_WordWrap: Integer; safecall;
        procedure Set_WordWrap(Value: Integer); safecall;
        function Get_Kind: Integer; safecall;
        procedure Set_Kind(Value: Integer); safecall;
        function Get_Layout: Integer; safecall;
        procedure Set_Layout(Value: Integer); safecall;
        function Get_Margin: Integer; safecall;
        procedure Set_Margin(Value: Integer); safecall;
        function Get_NumGlyphs: Integer; safecall;
        procedure Set_NumGlyphs(Value: Integer); safecall;
        function Get_Style: Integer; safecall;
        procedure Set_Style(Value: Integer); safecall;
        function Get_Spacing: Integer; safecall;
        procedure Set_Spacing(Value: Integer); safecall;
    end;


{---------------------------------------}
{---------------------------------------}
{---------------------------------------}
implementation


constructor TExControlBitBtn.Create(control: TTntBitBtn);
begin
     _control := control; 
end;

function TExControlBitBtn.Get_ControlType: ExodusControlTypes;
begin
    Result := ExodusControlBitBtn;
end;

function TExControlBitBtn.Get_Name: Widestring;
begin
      Result := _control.Name;
end;

procedure TExControlBitBtn.Set_Name(const Value: Widestring);
begin
      _control.Name := Value;
end;

function TExControlBitBtn.Get_Tag: Integer;
begin
      Result := _control.Tag;
end;

procedure TExControlBitBtn.Set_Tag(Value: Integer);
begin
      _control.Tag := Value;
end;

function TExControlBitBtn.Get_Left: Integer;
begin
      Result := _control.Left;
end;

procedure TExControlBitBtn.Set_Left(Value: Integer);
begin
      _control.Left := Value;
end;

function TExControlBitBtn.Get_Top: Integer;
begin
      Result := _control.Top;
end;

procedure TExControlBitBtn.Set_Top(Value: Integer);
begin
      _control.Top := Value;
end;

function TExControlBitBtn.Get_Width: Integer;
begin
      Result := _control.Width;
end;

procedure TExControlBitBtn.Set_Width(Value: Integer);
begin
      _control.Width := Value;
end;

function TExControlBitBtn.Get_Height: Integer;
begin
      Result := _control.Height;
end;

procedure TExControlBitBtn.Set_Height(Value: Integer);
begin
      _control.Height := Value;
end;

function TExControlBitBtn.Get_Cursor: Integer;
begin
      Result := _control.Cursor;
end;

procedure TExControlBitBtn.Set_Cursor(Value: Integer);
begin
      _control.Cursor := Value;
end;

function TExControlBitBtn.Get_Hint: Widestring;
begin
      Result := _control.Hint;
end;

procedure TExControlBitBtn.Set_Hint(const Value: Widestring);
begin
      _control.Hint := Value;
end;

function TExControlBitBtn.Get_HelpType: Integer;
begin
    if (_control.HelpType = htKeyword) then Result := 0;
    if (_control.HelpType = htContext) then Result := 1;
end;

procedure TExControlBitBtn.Set_HelpType(Value: Integer);
begin
   if (Value = 0) then _control.HelpType := htKeyword;
   if (Value = 1) then _control.HelpType := htContext;
end;

function TExControlBitBtn.Get_HelpKeyword: Widestring;
begin
      Result := _control.HelpKeyword;
end;

procedure TExControlBitBtn.Set_HelpKeyword(const Value: Widestring);
begin
      _control.HelpKeyword := Value;
end;

function TExControlBitBtn.Get_HelpContext: Integer;
begin
      Result := _control.HelpContext;
end;

procedure TExControlBitBtn.Set_HelpContext(Value: Integer);
begin
      _control.HelpContext := Value;
end;

function TExControlBitBtn.Get_BiDiMode: Integer;
begin
    if (_control.BiDiMode = bdLeftToRight) then Result := 0;
    if (_control.BiDiMode = bdRightToLeft) then Result := 1;
    if (_control.BiDiMode = bdRightToLeftNoAlign) then Result := 2;
    if (_control.BiDiMode = bdRightToLeftReadingOnly) then Result := 3;
end;

procedure TExControlBitBtn.Set_BiDiMode(Value: Integer);
begin
   if (Value = 0) then _control.BiDiMode := bdLeftToRight;
   if (Value = 1) then _control.BiDiMode := bdRightToLeft;
   if (Value = 2) then _control.BiDiMode := bdRightToLeftNoAlign;
   if (Value = 3) then _control.BiDiMode := bdRightToLeftReadingOnly;
end;

function TExControlBitBtn.Get_Cancel: Integer;
begin
    if (_control.Cancel = False) then Result := 0;
    if (_control.Cancel = True) then Result := 1;
end;

procedure TExControlBitBtn.Set_Cancel(Value: Integer);
begin
   if (Value = 0) then _control.Cancel := False;
   if (Value = 1) then _control.Cancel := True;
end;

function TExControlBitBtn.Get_Caption: Widestring;
begin
      Result := _control.Caption;
end;

procedure TExControlBitBtn.Set_Caption(const Value: Widestring);
begin
      _control.Caption := Value;
end;

function TExControlBitBtn.Get_Default: Integer;
begin
    if (_control.Default = False) then Result := 0;
    if (_control.Default = True) then Result := 1;
end;

procedure TExControlBitBtn.Set_Default(Value: Integer);
begin
   if (Value = 0) then _control.Default := False;
   if (Value = 1) then _control.Default := True;
end;

function TExControlBitBtn.Get_DragCursor: Integer;
begin
      Result := _control.DragCursor;
end;

procedure TExControlBitBtn.Set_DragCursor(Value: Integer);
begin
      _control.DragCursor := Value;
end;

function TExControlBitBtn.Get_DragKind: Integer;
begin
    if (_control.DragKind = dkDrag) then Result := 0;
    if (_control.DragKind = dkDock) then Result := 1;
end;

procedure TExControlBitBtn.Set_DragKind(Value: Integer);
begin
   if (Value = 0) then _control.DragKind := dkDrag;
   if (Value = 1) then _control.DragKind := dkDock;
end;

function TExControlBitBtn.Get_DragMode: Integer;
begin
    if (_control.DragMode = dmManual) then Result := 0;
    if (_control.DragMode = dmAutomatic) then Result := 1;
end;

procedure TExControlBitBtn.Set_DragMode(Value: Integer);
begin
   if (Value = 0) then _control.DragMode := dmManual;
   if (Value = 1) then _control.DragMode := dmAutomatic;
end;

function TExControlBitBtn.Get_Enabled: Integer;
begin
    if (_control.Enabled = False) then Result := 0;
    if (_control.Enabled = True) then Result := 1;
end;

procedure TExControlBitBtn.Set_Enabled(Value: Integer);
begin
   if (Value = 0) then _control.Enabled := False;
   if (Value = 1) then _control.Enabled := True;
end;

function TExControlBitBtn.Get_Font: IExodusControlFont;
begin
      Result := TExControlFont.Create(TFont(_control.Font));
end;

function TExControlBitBtn.Get_ModalResult: Integer;
begin
      Result := _control.ModalResult;
end;

procedure TExControlBitBtn.Set_ModalResult(Value: Integer);
begin
      _control.ModalResult := Value;
end;

function TExControlBitBtn.Get_ParentBiDiMode: Integer;
begin
    if (_control.ParentBiDiMode = False) then Result := 0;
    if (_control.ParentBiDiMode = True) then Result := 1;
end;

procedure TExControlBitBtn.Set_ParentBiDiMode(Value: Integer);
begin
   if (Value = 0) then _control.ParentBiDiMode := False;
   if (Value = 1) then _control.ParentBiDiMode := True;
end;

function TExControlBitBtn.Get_ParentFont: Integer;
begin
    if (_control.ParentFont = False) then Result := 0;
    if (_control.ParentFont = True) then Result := 1;
end;

procedure TExControlBitBtn.Set_ParentFont(Value: Integer);
begin
   if (Value = 0) then _control.ParentFont := False;
   if (Value = 1) then _control.ParentFont := True;
end;

function TExControlBitBtn.Get_ParentShowHint: Integer;
begin
    if (_control.ParentShowHint = False) then Result := 0;
    if (_control.ParentShowHint = True) then Result := 1;
end;

procedure TExControlBitBtn.Set_ParentShowHint(Value: Integer);
begin
   if (Value = 0) then _control.ParentShowHint := False;
   if (Value = 1) then _control.ParentShowHint := True;
end;

function TExControlBitBtn.Get_PopupMenu: IExodusControlPopupMenu;
begin
      Result := TExControlPopupMenu.Create(TTntPopupMenu(_control.PopupMenu));
end;

function TExControlBitBtn.Get_ShowHint: Integer;
begin
    if (_control.ShowHint = False) then Result := 0;
    if (_control.ShowHint = True) then Result := 1;
end;

procedure TExControlBitBtn.Set_ShowHint(Value: Integer);
begin
   if (Value = 0) then _control.ShowHint := False;
   if (Value = 1) then _control.ShowHint := True;
end;

function TExControlBitBtn.Get_TabOrder: Integer;
begin
      Result := _control.TabOrder;
end;

procedure TExControlBitBtn.Set_TabOrder(Value: Integer);
begin
      _control.TabOrder := Value;
end;

function TExControlBitBtn.Get_TabStop: Integer;
begin
    if (_control.TabStop = False) then Result := 0;
    if (_control.TabStop = True) then Result := 1;
end;

procedure TExControlBitBtn.Set_TabStop(Value: Integer);
begin
   if (Value = 0) then _control.TabStop := False;
   if (Value = 1) then _control.TabStop := True;
end;

function TExControlBitBtn.Get_Visible: Integer;
begin
    if (_control.Visible = False) then Result := 0;
    if (_control.Visible = True) then Result := 1;
end;

procedure TExControlBitBtn.Set_Visible(Value: Integer);
begin
   if (Value = 0) then _control.Visible := False;
   if (Value = 1) then _control.Visible := True;
end;

function TExControlBitBtn.Get_WordWrap: Integer;
begin
    if (_control.WordWrap = False) then Result := 0;
    if (_control.WordWrap = True) then Result := 1;
end;

procedure TExControlBitBtn.Set_WordWrap(Value: Integer);
begin
   if (Value = 0) then _control.WordWrap := False;
   if (Value = 1) then _control.WordWrap := True;
end;

function TExControlBitBtn.Get_Kind: Integer;
begin
    if (_control.Kind = bkCustom) then Result := 0;
    if (_control.Kind = bkOK) then Result := 1;
    if (_control.Kind = bkCancel) then Result := 2;
    if (_control.Kind = bkHelp) then Result := 3;
    if (_control.Kind = bkYes) then Result := 4;
    if (_control.Kind = bkNo) then Result := 5;
    if (_control.Kind = bkClose) then Result := 6;
    if (_control.Kind = bkAbort) then Result := 7;
    if (_control.Kind = bkRetry) then Result := 8;
    if (_control.Kind = bkIgnore) then Result := 9;
    if (_control.Kind = bkAll) then Result := 10;
end;

procedure TExControlBitBtn.Set_Kind(Value: Integer);
begin
   if (Value = 0) then _control.Kind := bkCustom;
   if (Value = 1) then _control.Kind := bkOK;
   if (Value = 2) then _control.Kind := bkCancel;
   if (Value = 3) then _control.Kind := bkHelp;
   if (Value = 4) then _control.Kind := bkYes;
   if (Value = 5) then _control.Kind := bkNo;
   if (Value = 6) then _control.Kind := bkClose;
   if (Value = 7) then _control.Kind := bkAbort;
   if (Value = 8) then _control.Kind := bkRetry;
   if (Value = 9) then _control.Kind := bkIgnore;
   if (Value = 10) then _control.Kind := bkAll;
end;

function TExControlBitBtn.Get_Layout: Integer;
begin
    if (_control.Layout = blGlyphLeft) then Result := 0;
    if (_control.Layout = blGlyphRight) then Result := 1;
    if (_control.Layout = blGlyphTop) then Result := 2;
    if (_control.Layout = blGlyphBottom) then Result := 3;
end;

procedure TExControlBitBtn.Set_Layout(Value: Integer);
begin
   if (Value = 0) then _control.Layout := blGlyphLeft;
   if (Value = 1) then _control.Layout := blGlyphRight;
   if (Value = 2) then _control.Layout := blGlyphTop;
   if (Value = 3) then _control.Layout := blGlyphBottom;
end;

function TExControlBitBtn.Get_Margin: Integer;
begin
      Result := _control.Margin;
end;

procedure TExControlBitBtn.Set_Margin(Value: Integer);
begin
      _control.Margin := Value;
end;

function TExControlBitBtn.Get_NumGlyphs: Integer;
begin
      Result := _control.NumGlyphs;
end;

procedure TExControlBitBtn.Set_NumGlyphs(Value: Integer);
begin
      _control.NumGlyphs := Value;
end;

function TExControlBitBtn.Get_Style: Integer;
begin
    if (_control.Style = bsAutoDetect) then Result := 0;
    if (_control.Style = bsWin31) then Result := 1;
    if (_control.Style = bsNew) then Result := 2;
end;

procedure TExControlBitBtn.Set_Style(Value: Integer);
begin
   if (Value = 0) then _control.Style := bsAutoDetect;
   if (Value = 1) then _control.Style := bsWin31;
   if (Value = 2) then _control.Style := bsNew;
end;

function TExControlBitBtn.Get_Spacing: Integer;
begin
      Result := _control.Spacing;
end;

procedure TExControlBitBtn.Set_Spacing(Value: Integer);
begin
      _control.Spacing := Value;
end;




end.
